course = 'Python for Beginners'
print(course.upper())
print(course)
print(course.lower())
print(course.find('y'))
print(course.find('Y'))
print(course.find('FOR'))
print(course.find('for'))
print(course.replace('for', '4'))
print(('Python' in course))
